# https://hub.docker.com/r/contrastsecuritydemo/nodegoat

name: Full ZAP Scan - NodeGoat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    container: python:3.11  # or any image that has curl and can run your steps
    services:
      nodegoat:
        image: contrastsecuritydemo/nodegoat:1.3.0
        ports:
          - 4000:4000

    steps:
      - name: Install curl
        run: |
          apt-get update && apt-get install -y curl
    
      - name: Wait for NodeGoat to be ready
        run: |
          echo "Waiting for node goat to start..."
          for i in {1..30}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://nodegoat:4000/about)
            if [ "$STATUS" = "200" ]; then
              echo "NodeGoat is up!"
              exit 0
            fi
            echo "Still waiting... HTTP $STATUS"
            sleep 10
          done
          echo "NodeGoat did not start in time"
          exit 1
      
      - name: Run ZAP Full Scan (HTML + JUnit XML)
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://nodegoat:4000'
          fail_action: false
          cmd_options: '-a -x report_xml.xml -l WARN'
        continue-on-error: true

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: full-zap-reports-nodegoat
          path: |
            report_html.html
            report_json.json
            report_md.md
            report_xml.xml
        continue-on-error: true

      - name: Publish ZAP JUnit Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: report_xml.xml
        continue-on-error: true
