name: Reusable IAC Workflow

on:
  workflow_call:
    inputs:
      language:
        type: string
        required: true
      project_dir:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      token:
        required: false
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

#####################################################################
# ===================== Generate TimeStamp for Name =====================
#####################################################################
  generate-timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set-timestamp.outputs.timestamp }}
    steps:
      - name: Generate Timestamp
        id: set-timestamp
        run: echo "TIMESTAMP=$(date +"%Y-%m-%d_GMT_%H.%M")" >> $GITHUB_OUTPUT
        
#####################################################################
# ===================== Custom IaC Scan =====================
#####################################################################
  custom-iac-scan:
    runs-on: ubuntu-latest
    needs: [generate-timestamp]
    env:
      TIMESTAMP: ${{ needs.generate-timestamp.outputs.timestamp }}
    # outputs set in the .sh file 
    outputs:
      artifact_name: ${{ steps.run-custom-iac-checkov-scan.outputs.ARTIFACT_NAME }}
      scan_results_dir: ${{ steps.run-custom-iac-checkov-scan.outputs.SCAN_RESULTS_DIR }}

    steps:
      - name: Checkout Project Repository - IAC
        uses: actions/checkout@v3

      # this tells the workflow to fetch files from the public 
      - name: Checkout Security-Scanning-Repo
        uses: actions/checkout@v3
        with:
          repository: marekboodt/Security-Scanning-Repo
          # specifies the directory where the repository will be cloned in the runner's workspace. path: security-scanning -- add same path later at name: Run SAST script
          path: security-scanning

# ===================== Run Custom IaC Scan =====================
      - name: Run IaC Custom *.sh scripts
        id: run-custom-iac-checkov-scan # set ID to later in artifact upload use need.<<ID>>.outputs.artifact_name
        run: |
          bash security-scanning/scripts/03-IAC/${{ inputs.language }}-iac.sh ${{ inputs.project_dir }} ${{ inputs.environment }} ${{ inputs.language }} ${{ env.TIMESTAMP }}
        # continue-on-error: true
        # If inputs.environment is 'non-prod', the pipeline will continue even if ./run-tests.sh fails. 
        # If inputs.environment is not 'non-prod' (e.g., 'prod'), the pipeline will stop if ./run-tests.sh fails
        continue-on-error: ${{ inputs.environment == 'non-prod' }}

# ===================== Upload Custom IaC Scan =====================
      - name: Upload scan results for next job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.language }}-ALL-IAC-SCANS-${{ inputs.environment }}-${{ TIMESTAMP }}
          path: ${{ steps.run-custom-iac-checkov-scan.outputs.SCAN_RESULTS_DIR }}
          
#####################################################################
# ===================== GitHub Action IaC Scan =====================
#####################################################################
  github-action-iac-scan:
    runs-on: ubuntu-latest
    needs: generate-timestamp
    env:
      TIMESTAMP: ${{ needs.generate-timestamp.outputs.timestamp }}
    steps:        
# ===================== Checkov as GitHub Action =====================
      - name: Create Checkov Scan Results Folder
        run: mkdir -p ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}  # Separate folder for Checkov action

      - name: Run Checkov Scan - CLI Output
        id: checkov-cli
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ inputs.project_dir }}
          framework: terraform
          output_format: cli
          output_file_path: ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}
          #/${{ inputs.language }}-IAC-Checkov-githubactions-scan-${{ inputs.environment }}-${{ env.TIMESTAMP }}.log
          log_level: WARNING
          container_user: 0
        continue-on-error: ${{ inputs.environment == 'non-prod' }}
      
      - name: Run Checkov Scan - SARIF Output
        id: checkov-sarif
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ inputs.project_dir }}
          framework: terraform
          output_format: sarif
          output_file_path: ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}
          # will write automatically in sarif format /${{ inputs.language }}-IAC-Checkov-githubactions-scan-${{ inputs.environment }}-${{ env.TIMESTAMP }}.sarif
          log_level: WARNING
          container_user: 0
        continue-on-error: ${{ inputs.environment == 'non-prod' }}

      - name: Run Checkov Scan - JSON Output
        id: checkov-json
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ inputs.project_dir }}
          framework: terraform
          output_format: json
          output_file_path: ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}
          # /${{ inputs.language }}-IAC-Checkov-githubactions-scan-${{ inputs.environment }}-${{ env.TIMESTAMP }}.json
          log_level: WARNING
          container_user: 0
        continue-on-error: ${{ inputs.environment == 'non-prod' }}

# ===================== Rename Checkov Output Files =====================
      - name: Rename Checkov Output Files
        run: |
          mv ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/results_json.json \
             ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/${{ inputs.language }}-IAC-Checkov-githubactions-scan-${{ inputs.environment }}-${{ env.TIMESTAMP }}.json
      
          mv ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/results_cli.txt \
             ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/${{ inputs.language }}-IAC-Checkov-githubactions-scan-${{ inputs.environment }}-${{ env.TIMESTAMP }}.log
      
          mv ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/results_sarif.sarif \
             ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/${{ inputs.language }}-IAC-Checkov-githubactions-scan-${{ inputs.environment }}-${{ env.TIMESTAMP }}.sarif

#####################################################################
# ===================== Custom IaC Artifact Upload ==================
#####################################################################
  iac-artifact-upload:
    runs-on: ubuntu-latest
    needs: [custom-iac-scan, generate-timestamp]
    env:
      TIMESTAMP: ${{ needs.generate-timestamp.outputs.timestamp }}
    steps:
# ===================== Download All Custom IAC Artifacts =====================
      - name: Download scan results from previous job
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.language }}-ALL-IAC-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}
# ===================== Save All Artifacts =====================
      - name: Save All IaC Scan Results as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.custom-iac-scan.outputs.ARTIFACT_NAME }}  # Folder name as artifact name
          path: ${{ needs.custom-iac-scan.outputs.SCAN_RESULTS_DIR }}  # Upload the entire folder
          # if-no-files-found: warn  # Prevent failure if the folder is empty
          if-no-files-found: ignore  # Avoids failure if all files were removed

#####################################################################
# ===================== Custom IaC Scan =====================
#####################################################################
  iac-gh-action-artifact-upload:
    runs-on: ubuntu-latest
    needs: [github-action-iac-scan]
    steps:
# ===================== Save Checkov GitHub Action Scan Results =====================
      - name: Save Checkov Scan Results as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}  # Timestamped artifact name
          path: ${{ inputs.language }}-ALL-IAC-GITHUB-ACTION-SCANS-${{ inputs.environment }}-${{ env.TIMESTAMP }}/  # Corrected folder path
          if-no-files-found: ignore
            
