name: Reusable SAST Workflow

on:
  workflow_call:
    inputs:
      type:
        type: string
        required: true
      language:
        type: string
        required: true
      project_dir:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      token:
        required: false
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project Repository - SAST
        uses: actions/checkout@v3

      # this tells the workflow to fetch files from the public 
      - name: Checkout Security-Scanning-Repo
        uses: actions/checkout@v3
        with:
          repository: marekboodt/Security-Scanning-Repo
          # specifies the directory where the repository will be cloned in the runner's workspace. path: security-scanning -- add same path later at name: Run SAST script
          path: security-scanning

#      - name: Debug File Structure
#        run: |
#          echo "Root Directory:"
#          ls -R
#          echo "Security-Scanning-Repo Directory:"
#          ls -R security-scanning


####################################################################
# CodeQL Scanning - Only available in Organizations - to be tested #
####################################################################
#      - name: Initiate CodeQL Scan V3
#        uses: github/codeql-action/init@v3
#        with:
#          languages: ${{ inputs.language }}

#      - name: Perform CodeQL Analysis V3
#        uses: github/codeql-action/analyze@v3
#        with:
#          languages: ${{ inputs.language }}

####################################################################
# Free Security Scanning Tools per Programming Language            #
####################################################################
      - name: Run Free SAST script
        run: |
          bash security-scanning/scripts/02-SAST/${{ inputs.language }}-sast.sh ${{ inputs.project_dir }} ${{ inputs.environment }}
#        continue-on-error: true
        # If inputs.environment is 'non-prod', the pipeline will continue even if ./run-tests.sh fails. 
        # If inputs.environment is not 'non-prod' (e.g., 'prod'), the pipeline will stop if ./run-tests.sh fails
        continue-on-error: ${{ inputs.environment == 'non-prod' }}

      - name: Save All SAST Results as in a Single Artifact Direcroty
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.SCAN_RESULTS_DIR }}

#########################
# SAVE SINGLE ARTIFACTS #
#########################
#      - name: Save Bandit JSON Output as Artifact
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ env.BANDIT_FILENAME }}
#          path: ${{ env.BANDIT_OUTPUT_FILE }}

