name: Reusable SAST Workflow

on:
  workflow_call:
    inputs:
      language:
        type: string
        required: true
      project_dir:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Django Repository
        uses: actions/checkout@v3

      - name: Checkout Security-Scanning-Repo
        uses: actions/checkout@v3
        with:
          repository: marekboodt/Security-Scanning-Repo
          path: security-scanning

      - name: Debug File Structure
        run: |
          echo "Root Directory:"
          ls -R
          echo "Security-Scanning-Repo Directory:"
          ls -R security-scanning

      - name: Run SAST script
        run: |
          bash security-scanning/scripts/sast/${{ inputs.language }}-sast.sh ${{ inputs.project_dir }}

#        continue-on-error: ${{ inputs.environment == 'non-prod' }}
