on:
  workflow_call:
    inputs:
      scantool: { type: string, required: true }
      language: { type: string, required: true }
      project_dir: { type: string, required: true }
      environment: { type: string, required: true }
    secrets:
      SEMGREP_APP_TOKEN: { required: false }

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  generate-timestamp:
    uses: ./.github/workflows/generate-timestamp.yml
  
  semgrep-fast-lightweight-scan-sarif-output:
    name: Semgrep SARIF Scan
    runs-on: ubuntu-latest
    needs: generate-timestamp
    continue-on-error: ${{ inputs.environment == 'non-prod' }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Semgrep scan with SARIF output
        run: semgrep scan --config p/ci --sarif -o semgrep-results-${{ needs.generate-timestamp.outputs.timestamp }}.sarif --error
        
      - name: Upload SARIF results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif-lightweight-results
          path: semgrep-results-${{ needs.generate-timestamp.outputs.timestamp }}.sarif

      - name: Upload Semgrep SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results-${{ needs.generate-timestamp.outputs.timestamp }}.sarif

# https://semgrep.dev/orgs/ 
  semgrep-deep-scan:
    name: semgrep/ci deep scan SARIF output
    runs-on: ubuntu-latest
    needs: generate-timestamp
    continue-on-error: ${{ inputs.environment == 'non-prod' }}
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci --sarif --output=semgrep-results-deep-scan-${{ needs.generate-timestamp.outputs.timestamp }}.sarif
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep-results-deep-scan-${{ needs.generate-timestamp.outputs.timestamp }}.sarif
    - name: Upload SARIF file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-sarif-deep-scan
        path: semgrep-results-deep-scan-${{ needs.generate-timestamp.outputs.timestamp }}.sarif
