name: Reusable SAST Workflow

on:
  workflow_call:
    inputs:
      language:
        type: string
        required: true
      project_dir:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with token
        env:
          PAT: ${{ secrets.token }}
        run: |
          echo "Authenticated with token"

      - name: Run SAST script
        run: |
          ls -R
          bash ./scripts/sast/${{ inputs.language }}-sast.sh ${{ inputs.project_dir }}
#        continue-on-error: ${{ inputs.environment == 'non-prod' }}
