name: Reusable SAST Checkov GH actions Workflow
# https://github.com/marketplace/actions/checkov-github-action
on:
  workflow_call:
    inputs:
      scantool:
        type: string
        required: true
      language:
        type: string
        required: false
      project_dir:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      SEMGREP_APP_TOKEN:
        required: false
      SONAR_TOKEN:
        required: false
      BEARER_TOKEN:
        required: false
      CODEQL_TOKEN:
        required: false
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab

permissions:
  actions: read
  contents: read
  security-events: write

#####################################################################
# ===================== GitHub Action SAST Scan =====================
#####################################################################
### the list to test with official github actions 
# Semgrep - multi lang
# Sonarqube - con Heavy setup, some paid features
# Bearer - multi lang
# CodeQL - multi lang
jobs:
  Semgrep-Scan:
    if: ${{ inputs.scantool == 'semgrep' }}
    uses: ./.github/workflows/sast-semgrep-workflow.yml
    with:
      scantool: ${{ inputs.scantool }}
#      language: ${{ inputs.language }}
      project_dir: ${{ inputs.project_dir }}
      environment: ${{ inputs.environment }}
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  CodeQL-Scan:
    if: ${{ inputs.scantool == 'codeql' }}
    uses: ./.github/workflows/sast-codeql-workflow.yml
    with:
      scantool: ${{ inputs.scantool }}
      language: ${{ inputs.language }}
      project_dir: ${{ inputs.project_dir }}
      environment: ${{ inputs.environment }}
    secrets:
      CODEQL_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  Bearer-Scan:
    if: ${{ inputs.scantool == 'bearer' }}
    uses: ./.github/workflows/sast-bearer-workflow.yml
    with:
      scantool: ${{ inputs.scantool }}
#      language: ${{ inputs.language }}
      project_dir: ${{ inputs.project_dir }}
      environment: ${{ inputs.environment }}
    secrets:
      CODEQL_TOKEN: ${{ secrets.BEARER_TOKEN }}

