on:
  workflow_call:
    inputs:
      scantool: { type: string, required: true }
#      language: { type: string, required: true }
      project_dir: { type: string, required: true }
      environment: { type: string, required: true }
    secrets:
      BEARER_TOKEN: { required: false }

permissions:
  actions: read
  contents: read
  security-events: write
 
jobs:
  generate-timestamp:
    uses: ./.github/workflows/generate-timestamp.yml


  bearer-scan:
    name: Bearer SAST scan SARIF output
    runs-on: ubuntu-latest
    needs: generate-timestamp
    env:
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
    steps:
      - uses: actions/checkout@v4
  
      - name: Run Bearer scan
        run: |
          npx bearer scan ${{ inputs.project_dir }} --format sarif --output bearer-results-scan-${{ needs.generate-timestamp.outputs.timestamp }}.sarif
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        continue-on-error: ${{ inputs.environment == 'non-prod' }}
  
      - name: Upload SARIF file to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bearer-results-scan-${{ needs.generate-timestamp.outputs.timestamp }}.sarif
  
      - name: Upload SARIF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bearer-sarif-scan
          path: bearer-results-scan-${{ needs.generate-timestamp.outputs.timestamp }}.sarif


  rule_check_bearer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
