on:
  workflow_call:
    inputs:
      scantool: { type: string, required: true }
#      language: { type: string, required: true }
      project_dir: { type: string, required: true }
      environment: { type: string, required: true }
    secrets:
      BEARER_TOKEN: { required: false }

permissions:
  actions: read
  contents: read
  security-events: write
 
jobs:
  generate-timestamp:
    uses: ./.github/workflows/generate-timestamp.yml

  bearer_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        continue-on-error: ${{ inputs.environment == 'non-prod' }}
