name: Security Scanning Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  Security-Scanning-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Inputs
        run: echo "DEBUG: Workflow started"

      - name: Print message from Main Workflow
        run: echo "Received message: ${{ inputs.message }}"
        
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the entire repository, not just the shallow clone
          repository: marekboodt/Security-Scanning-Repo

      - name: List All Files (Recursive)
        run: ls -R

      - name: Run test script
        run: ./scripts/test/test_script.sh
