# File: .github/workflows/SSR_test_workflow.yml
name: Security Scanning Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Display incoming message
        run: echo "Received message: ${{ inputs.message }}"

      - name: Run test script
        run: ./scripts/test/test_script.sh
