name: Security Scanning Workflow

on:
  workflow_call:
    inputs:
      message:  # message that has to be set in the main Workflow YML file.
        required: true
        type: string

jobs:
  Security-Scanning-Repo:
    runs-on: ubuntu-latest
    steps:
      # Print the message given in the main Workflow YML file
      - name: Print Message From Main Workflow
        run: |
          echo "Received message: ${{ inputs.message }}"

      - name: Check out Security-Scanning-Repo
        uses: actions/checkout@v3
        with:
          # Ensure full history and all branches are fetched
          fetch-depth: 0
          # Specify the repository to fetch (important for reusable workflows)
          repository: marekboodt/Security-Scanning-Repo
          # Explicitly fetch the main branch
          ref: main

      # Verify the full history and all branches are fetched.
      - name: Verify Repository Files
        run: ls -R  # Debug step to verify scripts/test/test_script.sh is available

      # Run another script that is in another folder. 
      - name: Run Test Script
        run: |
          chmod +x ./scripts/test/test_script.sh
          ./scripts/test/test_script.sh
