name: Security Scanning Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  Security-Scanning-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Inputs
        run: |
          echo "DEBUG: Workflow started"
          echo "Received message: ${{ inputs.message }}"
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the entire repository, not just the shallow clone

      - name: List All Files (Recursive)
        run: ls -R

      - name: Change Permissions for Test Script
        run: chmod +x ./scripts/test/test_script.sh

      - name: Run test script
        run: |
          chmod +x ./scripts/test/test_script.sh
          ./scripts/test/test_script.sh
